In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [7]:
arr = np.array(my_list)

In [9]:
arr


array([1, 2, 3])

In [11]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [23]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(5)

array([0.94335734, 0.80355417, 0.85297725, 0.8723401 , 0.00513256])

In [31]:
np.random.rand(5,5)

array([[0.93964302, 0.74127134, 0.04200235, 0.762038  , 0.10917748],
       [0.76594695, 0.64938744, 0.19853604, 0.24957869, 0.80837939],
       [0.04359833, 0.56953499, 0.07813018, 0.57349161, 0.05875731],
       [0.95882224, 0.13615466, 0.72507977, 0.91158514, 0.12403425],
       [0.87697299, 0.32339435, 0.04417987, 0.75743868, 0.41123658]])

In [33]:
np.random.randn(2)

array([ 1.3881954 , -0.85026856])

In [37]:
np.random.randint(1,100, 10)

array([80, 46, 79, 36, 46, 24, 57, 14, 80, 70], dtype=int32)

In [39]:
arr = np.arange(25)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
ranarr = np.random.randint(0,50,10)

In [45]:
ranarr

array([ 3,  0, 42, 47, 15, 23, 21,  2,  3,  5], dtype=int32)

In [47]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
ranarr

array([ 3,  0, 42, 47, 15, 23, 21,  2,  3,  5], dtype=int32)

In [51]:
ranarr.max()

np.int32(47)

In [53]:
ranarr.min()

np.int32(0)

In [55]:
ranarr.argmax()

np.int64(3)

In [57]:
ranarr.argmin()


np.int64(1)

In [59]:
from numpy.random import randint

In [61]:
randint(2,10)

2