In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

np.int64(8)

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [11]:
arr[0:5]


array([0, 1, 2, 3, 4])

In [13]:
arr[:6}

SyntaxError: closing parenthesis '}' does not match opening parenthesis '[' (3429588372.py, line 1)

In [15]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [17]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [19]:
arr[0:5] = 100

In [21]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [23]:
arr.np.arange(0,11)

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [25]:
arr = np.arange(0,11)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
slice_of_arr = arr[0:6]

In [31]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [33]:
arr_copy = arr.copy()

In [35]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])


In [39]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
arr_2d[0][0]

np.int64(5)

In [43]:
arr_2d[2,1]

np.int64(40)

In [45]:
arr = np.arange(1,11)

In [47]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [51]:
bool_arr = arr > 5

In [53]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [55]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [57]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [59]:
arr_2d = np.arange(50).reshape(5,10)

In [61]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [63]:
arr_2d[3,2]

np.int64(32)

In [65]:
arr_2d[2,3]

np.int64(23)

In [67]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])